post http://localhost:3000/signup
Content-Type: application/json

{
    "fullName": "Victor Mburu Mwaura",
    "email": "victormwaura@gmail.com",
    "telephone": "07898989898",
    "password": "123456"
}

####
get http://localhost:3005


###
get http://localhost:3005/products

###
post http://localhost:3005/products/add-product
Content-Type: application/json

{
    "imageUrl":"https://images.unsplash.com/photo-1512212621149-107ffe572d2f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c29mYXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    "productName":"Soft silk 2-seater",
    "price":"35500",
    "description":"This is your ideal resting compaion. An all time chair to suit you.",
    "categoryId": 1
}