post http://localhost:3000/signup
Content-Type: application/json

{
    "fullName": "Victor Mburu Mwaura",
    "email": "victormwaura@gmail.com",
    "telephone": "07898989898",
    "password": "123456"
}

####
get http://localhost:3011
